name: Docker Image CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/*
  pull_request:
    paths-ignore:
      - README.md
      - .github/workflows/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)
